### ISSUE TITLE
Can you please make the LLFF datasets public again?

### ISSUE THREAD

**Issue by hyunkoome** [postech-ami/FPRF#1]
Dear

The Google Drive link you made public (https://drive.google.com/drive/folders/128yBriW1IG_3NJ5Rp7APSTZsJqdJdfc1) does not contain the LLFF datasets.

Can you please make the LLFF datasets public again?

**Comment by Kim-GeonU** [comment]
Oh.. Sorry for the late response. Can you try downloading the dataset in this link?

https://www.kaggle.com/datasets/arenagrenade/llff-dataset-full

Thank you for letting me know about the issue.
